# Generated by Django 4.2.5 on 2023-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_query', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'text_query',
            },
        ),
    ]
